controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_consumer:
    path: /api/consumer
    methods: [POST]
    defaults:
         _controller: App\Controller\ConsumerController::index  
app_consumer_post:
    path: /api/consumer/post
    methods: [POST]
    defaults:
         _controller: App\Controller\ConsumerController::post          
app_consumer_auth:    
    path: /api/auth/consumer
    methods: [GET]
    defaults:
         _controller: App\Controller\ConsumerController::auth  