controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_consumer:
    path: /api/consumer
    methods: [POST,OPTIONS]
    defaults:
         _controller: App\Controller\ConsumerController::index  
      
app_consumer_auth:    
    path: /auth/consumer
    methods: [POST,OPTIONS]
    defaults:
         _controller: App\Controller\ConsumerController::auth  
app_error_cust:    
    path: /error-cust
    methods: [GET,OPTIONS]
    defaults:
         _controller: App\Controller\ErrorController::index
app_login:    
    path: /login
    methods: [GET,OPTIONS]
    defaults:
         _controller: App\Controller\LoginController::index   
app_user:
    path: /api/user/{id}
    methods: [GET,OPTIONS]
    defaults:
         _controller: App\Controller\ConsumerController::user                           